workflows:
  android-workflow:
    name: Compilation Aktual Android
    environment:
      java: 21
    scripts:
      - name: Compiler l'APK Android
        script: |
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - '**/build/outputs/apk/**/*.apk'
